#!/usr/bin/env python3
"""Generate typed SysV-to-Windows OpenGL thunks for the x32 Xbox guest with native Direct3D 11 backend."""
import re
import sys


def main():
    guest_c, output = sys.argv[1:3]
    text = open(guest_c, encoding="utf-8").read()
    declarations = re.findall(r"^([A-Za-z_][A-Za-z0-9_ \t*]*?)\s+(hostgl_(gl\w+))\((.*?)\);$", text, re.M)
    lines = [
        "/* generated by tools/xbox_host_gl.py; do not edit; Direct3D 11 native backend */",
        '#include "host.h"',
        '#include "d3d8_dx11.h"',
        "#include <SDL.h>",
        "#include <SDL_opengl.h>",
        "#include <string.h>",
        "",
        "static uint32_t s_d3d11_id_counter = 100;",
        "",
    ]
    names = []
    for ret, host_name, gl_name, params in declarations:
        params = params.strip()
        plist = [] if params in ("", "void") else [p.strip() for p in params.split(",")]
        args = []
        named = []
        for i, param in enumerate(plist):
            name = f"a{i}"
            named.append(f"{param} {name}")
            args.append(name)
        signature = ", ".join(named) or "void"

        if gl_name == "glShaderSource":
            lines += [
                f"void GUEST_ABI {host_name}(GLuint shader, GLsizei count, const unsigned long long *strings, const GLint *lengths)",
                "{",
                "    (void)shader; (void)count; (void)strings; (void)lengths;",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glCreateShader":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    (void)a0; return (GLuint)(++s_d3d11_id_counter);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glCreateProgram":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    return (GLuint)(++s_d3d11_id_counter);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glCheckFramebufferStatus":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    (void)a0; return 0x8CD5; /* GL_FRAMEBUFFER_COMPLETE */",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name in ("glGenTextures", "glGenBuffers", "glGenFramebuffers", "glGenRenderbuffers", "glGenVertexArrays", "glGenQueries"):
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    if (a1) { for (GLsizei i = 0; i < a0; ++i) a1[i] = ++s_d3d11_id_counter; }",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glGetShaderiv":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    (void)a0; if (!a2) return;",
                "    if (a1 == 0x8B81) *a2 = 1; /* GL_COMPILE_STATUS */",
                "    else if (a1 == 0x8B84) *a2 = 0; /* GL_INFO_LOG_LENGTH */",
                "    else *a2 = 1;",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glGetProgramiv":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    (void)a0; if (!a2) return;",
                "    if (a1 == 0x8B82) *a2 = 1; /* GL_LINK_STATUS */",
                "    else if (a1 == 0x8B84) *a2 = 0; /* GL_INFO_LOG_LENGTH */",
                "    else *a2 = 1;",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glGetIntegerv":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    if (!a1) return;",
                "    switch (a0) {",
                "    case 0x821D: *a1 = 0; break; /* GL_NUM_EXTENSIONS */",
                "    case 0x0D33: *a1 = 4096; break; /* GL_MAX_TEXTURE_SIZE */",
                "    case 0x8B4D: *a1 = 16; break; /* GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS */",
                "    case 0x8869: *a1 = 16; break; /* GL_MAX_VERTEX_ATTRIBS */",
                "    case 0x84E8: *a1 = 4096; break; /* GL_MAX_RENDERBUFFER_SIZE */",
                "    case 0x84E2: *a1 = 4; break; /* GL_MAX_DRAW_BUFFERS */",
                "    default: *a1 = 0; break;",
                "    }",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glViewport":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    d3d8_dx11_set_viewport((DWORD)a0, (DWORD)a1, (DWORD)a2, (DWORD)a3, 0.0f, 1.0f);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glClear":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    d3d8_dx11_clear((DWORD)a0, 0, 1.0f, 0);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glDrawArrays":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    d3d8_dx11_draw_vertices((DWORD)a0, (DWORD)a1, (DWORD)a2);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glDrawElements":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    d3d8_dx11_draw_indexed_vertices((DWORD)a0, (DWORD)a1, (const uint16_t *)(uintptr_t)a3);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        if gl_name == "glGetUniformLocation":
            lines += [
                f"{ret} GUEST_ABI {host_name}({signature})",
                "{",
                "    (void)a0; (void)a1; return -1;",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue

        # Default fallback stub
        lines += [
            f"{ret} GUEST_ABI {host_name}({signature})",
            "{",
            *[f"    (void){a};" for a in args],
            f"    return{' (' + ret + ')0' if ret != 'void' else ''};",
            "}", "",
        ]
        names.append((host_name, gl_name))

    lines += [
        "static const struct { const char *name; void *function; } xbox_gl_imports[] = {",
        *[f'    {{ "{gl}", (void *){host} }},' for host, gl in names],
        "};", "",
        "void *host_gl_resolve(const char *name)", "{",
        "    size_t i; for (i = 0; i < sizeof(xbox_gl_imports)/sizeof(xbox_gl_imports[0]); ++i)",
        "        if (!strcmp(name, xbox_gl_imports[i].name)) return xbox_gl_imports[i].function;",
        "    return NULL;", "}", "",
        "void GUEST_ABI host_gl_get_string(uint32_t name, int index, char *buffer, uint32_t size)", "{",
        "    const char *text = NULL;",
        "    (void)index;",
        "    switch (name) {",
        '    case 0x1F00: text = "Microsoft"; break;',
        '    case 0x1F01: text = "Xbox One Durango D3D11"; break;',
        '    case 0x1F02: text = "OpenGL ES 3.2 (Direct3D 11 Native)"; break;',
        '    case 0x8B8C: text = "OpenGL ES GLSL ES 3.20"; break;',
        '    default: text = ""; break;',
        "    }",
        "    if (size && buffer) {",
        "        strncpy(buffer, text, size - 1);",
        "        buffer[size - 1] = 0;",
        "    }",
        "}",
        "int GUEST_ABI host_gl_has_extension(const char *name)", "{",
        "    (void)name;",
        "    return 1;",
        "}", "",
        "uint32_t GUEST_ABI host_gl_read_buffer(uint32_t buffer, uint32_t offset) { (void)buffer; (void)offset; return 0; }",
        "uint32_t GUEST_ABI host_gl_read_buffer_word(uint32_t buffer, uint32_t offset) { (void)buffer; (void)offset; return 0; }",
        "void GUEST_ABI host_gl_buffer_write(uint32_t target, uint32_t offset, uint32_t size, const void *data) { (void)target; (void)offset; (void)size; (void)data; }",
        "void GUEST_ABI host_gl_fence_frame(uint32_t slot) { (void)slot; }",
        "void GUEST_ABI host_gl_wait_frame(uint32_t slot) { (void)slot; }",
    ]
    with open(output, "w", encoding="utf-8") as out:
        out.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
