#!/usr/bin/env python3
"""Generate typed SysV-to-Windows OpenGL thunks for the x32 Xbox guest."""
import re
import sys


def main():
    guest_c, output = sys.argv[1:3]
    text = open(guest_c, encoding="utf-8").read()
    declarations = re.findall(r"^([A-Za-z_][A-Za-z0-9_ \t*]*?)\s+(hostgl_(gl\w+))\((.*?)\);$", text, re.M)
    lines = [
        "/* generated by tools/xbox_host_gl.py; do not edit */",
        '#include "host.h"',
        "#include <SDL.h>",
        "#include <SDL_opengl.h>",
        "#include <string.h>",
        "",
    ]
    names = []
    for ret, host_name, gl_name, params in declarations:
        params = params.strip()
        if gl_name == "glShaderSource":
            lines += [
                f"void GUEST_ABI {host_name}(GLuint shader, GLsizei count, const unsigned long long *strings, const GLint *lengths)",
                "{",
                "    const GLchar *native[16]; GLsizei i;",
                "    typedef void (APIENTRY *proc_t)(GLuint, GLsizei, const GLchar *const *, const GLint *);",
                "    static proc_t proc; if (!proc) proc = (proc_t)SDL_GL_GetProcAddress(\"glShaderSource\");",
                "    if (!proc) return;",
                "    if (count > 16) count = 16; for (i = 0; i < count; ++i) native[i] = (const GLchar *)(uintptr_t)strings[i];",
                "    proc(shader, count, native, lengths);",
                "}", "",
            ]
            names.append((host_name, gl_name))
            continue
        plist = [] if params in ("", "void") else [p.strip() for p in params.split(",")]
        args = []
        named = []
        for i, param in enumerate(plist):
            name = f"a{i}"
            named.append(f"{param} {name}")
            args.append(name)
        signature = ", ".join(named) or "void"
        call = f"proc({', '.join(args)})"
        lines += [
            f"{ret} GUEST_ABI {host_name}({signature})",
            "{",
            f"    typedef {ret} (APIENTRY *proc_t)({params or 'void'});",
            f"    static proc_t proc; if (!proc) proc = (proc_t)SDL_GL_GetProcAddress(\"{gl_name}\");",
            f"    if (!proc) return{' (' + ret + ')0' if ret != 'void' else ''};",
            f"    {'return ' if ret != 'void' else ''}{call};",
            "}", "",
        ]
        names.append((host_name, gl_name))
    lines += [
        "static const struct { const char *name; void *function; } xbox_gl_imports[] = {",
        *[f'    {{ "{gl}", (void *){host} }},' for host, gl in names],
        "};", "",
        "void *host_gl_resolve(const char *name)", "{",
        "    size_t i; for (i = 0; i < sizeof(xbox_gl_imports)/sizeof(xbox_gl_imports[0]); ++i)",
        "        if (!strcmp(name, xbox_gl_imports[i].name)) return xbox_gl_imports[i].function;",
        "    return NULL;", "}", "",
        "void GUEST_ABI host_gl_get_string(uint32_t name, int index, char *buffer, uint32_t size)", "{",
        "    const GLubyte *text = NULL;",
        "    if (index >= 0) { typedef const GLubyte *(APIENTRY *p_t)(GLenum, GLuint); static p_t p; if (!p) p=(p_t)SDL_GL_GetProcAddress(\"glGetStringi\"); if (p) text=p(name,index); }",
        "    else { typedef const GLubyte *(APIENTRY *p_t)(GLenum); static p_t p; if (!p) p=(p_t)SDL_GL_GetProcAddress(\"glGetString\"); if (p) text=p(name); }",
        "    if (size) { buffer[0]=0; if (text) { strncpy(buffer,(const char *)text,size-1); buffer[size-1]=0; } }", "}",
        "int GUEST_ABI host_gl_has_extension(const char *name)", "{",
        "    if (!name || !*name) return 0;",
        "    typedef const GLubyte *(APIENTRY *p_gsi_t)(GLenum, GLuint);",
        "    typedef void (APIENTRY *p_giv_t)(GLenum, GLint *);",
        "    static p_gsi_t p_gsi; static p_giv_t p_giv;",
        "    if (!p_gsi) p_gsi = (p_gsi_t)SDL_GL_GetProcAddress(\"glGetStringi\");",
        "    if (!p_giv) p_giv = (p_giv_t)SDL_GL_GetProcAddress(\"glGetIntegerv\");",
        "    if (p_gsi && p_giv) {",
        "        GLint num = 0; p_giv(GL_NUM_EXTENSIONS, &num);",
        "        for (GLint i = 0; i < num; ++i) {",
        "            const char *ext = (const char *)p_gsi(GL_EXTENSIONS, (GLuint)i);",
        "            if (ext && !strcmp(ext, name)) return 1;",
        "        }",
        "    }",
        "    return SDL_GL_ExtensionSupported(name) ? 1 : 0;",
        "}", "",
        "uint32_t GUEST_ABI host_gl_read_buffer(uint32_t buffer, uint32_t offset) { (void)buffer; (void)offset; return 0; }",
        "uint32_t GUEST_ABI host_gl_read_buffer_word(uint32_t buffer, uint32_t offset) { (void)buffer; (void)offset; return 0; }",
        "void GUEST_ABI host_gl_buffer_write(uint32_t target,uint32_t offset,uint32_t size,const void *data) { typedef void(APIENTRY*p_t)(GLenum,GLintptr,GLsizeiptr,const void*); static p_t p; if(!p)p=(p_t)SDL_GL_GetProcAddress(\"glBufferSubData\"); if(p)p(target,offset,size,data); }",
        "void GUEST_ABI host_gl_fence_frame(uint32_t slot) { (void)slot; }",
        "void GUEST_ABI host_gl_wait_frame(uint32_t slot) { (void)slot; }",
    ]
    with open(output, "w", encoding="utf-8") as out:
        out.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
